apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-elastic
  namespace: elastic
  labels:
    type: local
    app: elasticsearch-master
spec:
  storageClassName: gp2
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data-elastic"