apiVersion: v1
kind: Service
metadata:
  name: my-service-nginx
  namespace: artem-testing
spec:
  selector:
      app:  nginx # Selecting PODS with those Labels
  type:  LoadBalancer # LoadBalancer | ClusterIP | NodePort
  ports:
    - protocol: TCP
      port: 80      # Port on Load Balancer
      targetPort: 80  # Port on POD