# cluster.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: emulation
  region: eu-west-3

vpc:
  subnets:
    private:
      eu-north-1a: { id: subnet-0ff156e0c4a6d300c }
      eu-north-1b: { id: subnet-0549cdab573695c03 }
      eu-north-1c: { id: subnet-0426fb4a607393184 }

nodeGroups:
  - name: ng-1-workers
    labels: { role: workers }
    instanceType: t3.medium
    desiredCapacity: 4
    volumeSize: 80
  # - name: ng-2-builders
  #   labels: { role: builders }
  #   instanceType: m5.2xlarge
  #   desiredCapacity: 2
  #   privateNetworking: true
  #   iam:
  #     withAddonPolicies:
  #       imageBuilder: true
