apiVersion : apps/v1
kind : Deployment
metadata : 
  name : mariadb
  namespace: wsaa
  labels:
    db : mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-mariadb
  template:
    metadata:
      labels:
        app: db-mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.7.4
        env:
        - name: MARIADB_ROOT_PASSWORD
          value: "112233445566"
        - name: MARIADB_DATABASE # This variable allows you to specify the name of a database to be created on image startup.
          value: IntDB
        - name: MARIADB_USER
          value: user
        - name: MARIADB_PASSWORD
          value: userpassword 
        ports:
        - containerPort: 3306
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: task-pv-storagedb
      volumes:
      - name: task-pv-storagedb
        persistentVolumeClaim:
          claimName: task-pv-claim-mariadb