apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-mariadb
  namespace: wsaa
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/data/mariadb"