apiVersion: v1
kind: Service
metadata:
  name:  service-marisdb
spec:
  selector:
    #ui:  phpmyadmin # Selecting PODS with those Labels
    app: wsaa
  type:  NodePort # LoadBalancer | ClusterIP | NodePort
  ports:
  - name:  port-mariadb
    port:  3306        # Port on Load Balancer
    targetPort:  3306  # Port on POD