apiVersion: v1
kind: Service
metadata:
  name:  service-name-db
  namespace: wsaa
spec:
  selector:
    ui:  phpmyadmin # Selecting PODS with those Labels
    # app: db-mariadb
  type:  NodePort # LoadBalancer | ClusterIP | NodePort
  ports:
  - name:  port-phpmyadmin
    port:  80        # Port on Load Balancer
    targetPort:  80  # Port on POD
  # - name:  port-mariadb
  #   port:  3306        # Port on Load Balancer
  #   targetPort:  3306  # Port on POD