apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1-nfs
#  namespace: test-nfs
spec:
  capacity:
    storage: 8Gi
  # volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  nfs:
    path: /var/nfs/share
    server: 192.168.1.83 # IP NFS server

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv2-nfs
#  namespace: test-nfs
spec:
  capacity:
    storage: 2Gi
  # volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  nfs:
    path: /var/nfs/share
    server: 192.168.1.83 # IP NFS server