apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: prometheus-scaledobject
  namespace: testing
spec:
  scaleTargetRef:
    name: nginx-deployment-testing
  # pollingInterval: 30                               
  # cooldownPeriod:  120                              
  # minReplicaCount: 1                                
  # maxReplicaCount: 5                               
  # advanced:                                         
  #   restoreToOriginalReplicaCount: false            
  #   horizontalPodAutoscalerConfig:                  
  #     behavior:                                     
  #       scaleDown:
  #         stabilizationWindowSeconds: 300
  #         policies:
  #         - type: Percent
  #           value: 100
  #           periodSeconds: 15
  # triggers:
  # - type: prometheus
  #   metadata:
  #     serverAddress: http://prometheus-server.prometheus.svc.cluster.local:9090
  #     #metricName: http_requests_total # DEPRECATED: This parameter is deprecated as of KEDA v2.10 and will be removed in version 2.12
  #     threshold: '100'
  #     query: sum(nginx_http_requests_total)

  triggers:
  - type: prometheus
    metadata:
      # Required fields:
      serverAddress: http://prometheus-server.prometheus.svc.cluster.local:9090
      metricName: http_requests_total # DEPRECATED: This parameter is deprecated as of KEDA v2.10 and will be removed in version 2.12. Note: name to identify the metric, generated value would be `prometheus-http_requests_total`
      query: sum(rate(http_requests_total{deployment="my-deployment"}[2m])) # Note: query must return a vector/scalar single element response
      threshold: '100.50'
      activationThreshold: '5.5'
      # # Optional fields:
      # namespace: testing  # for namespaced queries, eg. Thanos
      # cortexOrgID: my-org # DEPRECATED: This parameter is deprecated as of KEDA v2.10 in favor of customHeaders and will be removed in version 2.12. Use custom headers instead to set X-Scope-OrgID header for Cortex. (see below)
      # customHeaders: X-Client-Id=cid,X-Tenant-Id=tid,X-Organization-Id=oid # Optional. Custom headers to include in query. In case of auth header, use the custom authentication or relevant authModes.
      # ignoreNullValues: false # Default is `true`, which means ignoring the empty value list from Prometheus. Set to `false` the scaler will return error when Prometheus target is lost
      # unsafeSsl: "false" #  Default is `false`, Used for skipping certificate check when having self signed certs for Prometheus endpoint    