kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  name: nginx
  namespace: testing
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  endpoints:
  - interval: 15s
    path: "/status/format/prometheus"
    port: http