apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name     : asterisk
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name     : in-cluster
    namespace: wsaa
  source:
    path   : "k8s/wsaa/asterisk"
    repoURL: "https://github.com/nkartem/k8s.git"
    targetRevision: HEAD

  project: default
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true