apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-name-mariadb-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mariadb
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50 # max 1000 . 1000 = 1 core 