apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1-nfs
#  namespace: test-nfs
spec:
  capacity:
    storage: 5Gi
  # volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  nfs:
    path: /mnt/nfs_shares/k8s
    server: 192.168.1.100 # IP NFS server