apiVersion : apps/v1
kind : Deployment
metadata : 
  name : my-phpmyadmin-autoscaling
  labels:
    webapp : phpmyadmin
    db : mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-web-app
  template:
    metadata:
      labels:
        app: db-web-app
    spec:
      containers:
      - name: phpmyadmin-web-app
        image: phpmyadmin:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 80

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-name-phpmyadmin-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: db-web-app
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
