apiVersion : apps/v1
kind : Deployment
metadata : 
  name : asterisk-deploy
  labels:
    app : asterisk-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asterisk
  template:
    metadata:
      labels:
        app: asterisk
    spec:
      containers:
      - name: asterisk
        image: nkartem/asterisk
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        command: ["/bin/bash", "-c", "systemctl start asterisk"]
        ports:
        - name:  sip
          containerPort:  5060
          protocol: UDP
        - name:  ssh
          containerPort:  5022
          protocol: TCP
        - name:  sip-10000
          containerPort: 10000
          protocol: UDP
        - name:  sip-10001
          containerPort: 10001
          protocol: UDP
        - name:  sip-10002
          containerPort: 10002
          protocol: UDP
        - name:  sip-10003
          containerPort: 10003
          protocol: UDP
        - name:  sip-10004
          containerPort: 10004
          protocol: UDP
        - name:  sip-10005
          containerPort: 10005
          protocol: UDP

        # - name:  sip-connect
        #   containerPort: '10000-20000'
        #   protocol: UDP
        volumeMounts:
        - mountPath: /etc/asterisk
          name: nfs-pvc-test
      
      volumes:
      - name:  nfs-pvc-test
        persistentVolumeClaim:
          claimName: nfs-pvc
      # - name: name-local-volume
      #   hostPath:
      #     # directory location on host
      #     path: /opt/podman/asterisk
      #     # this field is optional
      #     type: Directory



---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: asterisk-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: asterisk-deploy
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: v1
kind: Service
metadata:
  name:  service-asterisk
spec:
  selector:
    app:  asterisk # Selecting PODS with those Labels
  type:  NodePort # LoadBalancer | ClusterIP | NodePort
  ports:
  - name:  name-sip-port
    port:  5060        # Port on Load Balancer
    protocol: UDP
    targetPort:  sip  # Port on POD
  - name:  name-ssh-port
    port:  5022        # Port on Load Balancer
    targetPort:  ssh  # Port on POD
  - name:  name-10000
    port:  10000 # Port on Load Balancer
    protocol: UDP
    targetPort:  sip-10000  # Port on POD
  - name:  name-10001
    port:  10001 # Port on Load Balancer
    protocol: UDP
    targetPort:  sip-10001  # Port on POD
  - name:  name-10002
    port:  10002 # Port on Load Balancer
    protocol: UDP
    targetPort:  sip-10002  # Port on POD
  - name:  name-10003
    port:  10003 # Port on Load Balancer
    protocol: UDP
    targetPort:  sip-10003  # Port on POD
  - name:  name-10004
    port:  10004 # Port on Load Balancer
    protocol: UDP
    targetPort:  sip-10004  # Port on POD
  - name:  name-10005
    port:  10005 # Port on Load Balancer
    protocol: UDP
    targetPort:  sip-10005  # Port on POD
  # - name:  name-sip-connect-10000
  #   port:  10000-20000 # Port on Load Balancer
  #   targetPort:  sip-connect-10000  # Port on POD
---
# PV # For this config you need install NFS server https://www.linuxtechi.com/setup-nfs-server-on-centos-8-rhel-8/
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1-nfs
#  namespace: test-nfs
spec:
  capacity:
    storage: 5Gi
  # volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  nfs:
    path: /mnt/nfs_shares/k8s/asterisk
    server: 192.168.1.100 # IP NFS server
---
# PVC # For this config you need install NFS server https://www.linuxtechi.com/setup-nfs-server-on-centos-8-rhel-8/
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
#  namespace: test-nfs
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  volumeName: pv1-nfs