apiVersion : apps/v1
kind : Deployment
metadata : 
  name : deploy-phpmyadmin
  labels:
    db : label-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      ui: phpmyadmin
  template:
    metadata:
      labels:
        ui: phpmyadmin # Service will look for those PODS Labels!!!
    spec:
      containers:
      - name : container-phpmyadmin
        image: phpmyadmin:latest
        ports:
        - containerPort: 80
        env:
        - name: PMA_ARBITRARY
          value: "1" # when set to 1 connection to the arbitrary server will be allowed
        - name: PMA_HOST
          value: '127.0.0.1'
        - name: PMA_PORT
          value: "3306"
        - name: MARIADB_ROOT_PASSWORD
          value: secret