# kind: Namespace
# apiVersion: v1
# metadata:
#   name: elastic
# ---
# kind: Service
# apiVersion: v1
# metadata:
#   name: elasticsearch
#   namespace: elastic
#   labels:
#     app: elasticsearch
# spec:
#   selector:
#     app: elasticsearch
#   clusterIP: None
#   ports:
#     - port: 9200
#       name: rest
#     - port: 9300
#       name: inter-node
# ---
# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: es-cluster
#   namespace: elastic
# spec:
#   serviceName: elasticsearch
#   replicas: 1
#   selector:
#     matchLabels:
#       app: elasticsearch
#   template:
#     metadata:
#       labels:
#         app: elasticsearch
#     spec:
#       containers:
#       - name: elasticsearch
#         image: elasticsearch:7.17.10
#         resources:
#             limits:
#               cpu: 1000m
#             requests:
#               cpu: 100m
#         ports:
#         - containerPort: 9200
#           name: rest
#           protocol: TCP
#         - containerPort: 9300
#           name: inter-node
#           protocol: TCP
#         volumeMounts:
#         - name: elasticsearch-master-0
#           mountPath: /usr/share/elasticsearch/data
#         env:
#           - name: cluster.name
#             value: k8s-logs
#           - name: node.name
#             valueFrom:
#               fieldRef:
#                 fieldPath: metadata.name
#           # - name: discovery.seed_hosts
#           #   value: "es-cluster-0.elasticsearch,es-cluster-1.elasticsearch,es-cluster-2.elasticsearch"
#           # - name: cluster.initial_master_nodes
#           #   value: "es-cluster-0,es-cluster-1,es-cluster-2"
#           - name: ES_JAVA_OPTS
#             value: "-Xms512m -Xmx512m"
#       initContainers:
#       - name: fix-permissions
#         image: busybox
#         command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
#         securityContext:
#           privileged: true
#         volumeMounts:
#         - name: elasticsearch-master-0
#           mountPath: /usr/share/elasticsearch/data
#       - name: increase-vm-max-map
#         image: busybox
#         command: ["sysctl", "-w", "vm.max_map_count=262144"]
#         securityContext:
#           privileged: true
#       - name: increase-fd-ulimit
#         image: busybox
#         command: ["sh", "-c", "ulimit -n 65536"]
#         securityContext:
#           privileged: true
#   volumeClaimTemplates:
#   - metadata:
#       name: elasticsearch-master-0
#       labels:
#         app: elasticsearch
#     spec:
#       accessModes: [ "ReadWriteOnce" ]
#       storageClassName: nfs
#       resources:
#         requests:
#           storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-master-elasticsearch-master-0
  namespace: elastic
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
 #   - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  volumeName: pv3-nfs-elastic

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv3-nfs-elastic
  labels:
    app: elasticsearch
spec:
  capacity:
    storage: 30Gi
    #volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  nfs:
    path: /var/nfs/share
    server: 192.168.1.8 # IP NFS server



---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: example-nfs
provisioner: example.com/external-nfs
parameters:
  server: 192.168.1.8 # IP NFS server
  path: /var/nfs/share
  readOnly: "false"