apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv3-nfs-elastic 
#  namespace: test-nfs
spec:
  capacity:
    storage: 30Gi
  # volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  nfs:
    path: /var/nfs/share
    server: 192.168.1.8 # IP NFS server