apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-asterisk
  namespace: wsaa
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/data/asterisk"