# PVC # For this config you need install NFS server https://www.linuxtechi.com/setup-nfs-server-on-centos-8-rhel-8/
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  namespace: wsaa
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  volumeName: pv1-nfs