apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-asterisk
  namespace: wsaa
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi