apiVersion: v1
kind: Service
metadata:
  name:  service-asterisk
  namespace: wsaa
spec:
  selector:
    app:  asterisk # Selecting PODS with those Labels
  type:  NodePort # LoadBalancer | ClusterIP | NodePort
  ports:
  - name:  name-sip-port
    port:  5060        # Port on Load Balancer
    protocol: UDP
    targetPort:  sip  # Port on POD
  - name:  name-ssh-port
    port:  5022        # Port on Load Balancer
    protocol: UDP
    targetPort:  ssh  # Port on POD
  - name:  name-10000
    port:  10000 # Port on Load Balancer
    protocol: UDP
    targetPort:  sip-10000  # Port on POD
  - name:  name-10001
    port:  10001 # Port on Load Balancer
    protocol: UDP
    targetPort:  sip-10001  # Port on POD
  - name:  name-10002
    port:  10002 # Port on Load Balancer
    protocol: UDP
    targetPort:  sip-10002  # Port on POD
  - name:  name-10003
    port:  10003 # Port on Load Balancer
    protocol: UDP
    targetPort:  sip-10003  # Port on POD
  - name:  name-10004
    port:  10004 # Port on Load Balancer
    protocol: UDP
    targetPort:  sip-10004  # Port on POD
  - name:  name-10005
    port:  10005 # Port on Load Balancer
    protocol: UDP
    targetPort:  sip-10005  # Port on POD
  # - name:  name-sip-connect-10000
  #   port:  10000-20000 # Port on Load Balancer
  #   targetPort:  sip-connect-10000  # Port on POD